"""Add current_hit_dice to Character

Revision ID: 1966e105b307
Revises: 300c31dc4ee7
Create Date: 2025-05-30 17:04:29.174478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1966e105b307'
down_revision = '300c31dc4ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_hit_dice', sa.Integer(), nullable=False))

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_specific_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('level_specific_data')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('current_hit_dice')

    # ### end Alembic commands ###
