"""Add Weapon model and update Spell model for attack rolls

Revision ID: 230199b4558a
Revises: a1afaee6caee
Create Date: 2025-05-30 18:42:04.306929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230199b4558a'
down_revision = 'a1afaee6caee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.String(length=50), nullable=True),
    sa.Column('damage_dice', sa.String(length=20), nullable=False),
    sa.Column('damage_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('range', sa.String(length=50), nullable=True),
    sa.Column('normal_range', sa.Integer(), nullable=True),
    sa.Column('long_range', sa.Integer(), nullable=True),
    sa.Column('throw_range_normal', sa.Integer(), nullable=True),
    sa.Column('throw_range_long', sa.Integer(), nullable=True),
    sa.Column('is_martial', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('character_weapon_association',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('is_equipped_main_hand', sa.Boolean(), nullable=True),
    sa.Column('is_equipped_off_hand', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapon.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'weapon_id')
    )
    with op.batch_alter_table('spell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_attack_roll', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('spell_attack_ability', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spell', schema=None) as batch_op:
        batch_op.drop_column('spell_attack_ability')
        batch_op.drop_column('requires_attack_roll')

    op.drop_table('character_weapon_association')
    op.drop_table('weapon')
    # ### end Alembic commands ###
