"""Add CharacterLevel model and update Character model for level history

Revision ID: 300c31dc4ee7
Revises: 7fa7f56194f4
Create Date: 2025-05-29 17:38:24.498853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy.dialects import sqlite
from sqlalchemy import inspect # Added for checking table existence
import datetime


# revision identifiers, used by Alembic.
revision = '300c31dc4ee7'
down_revision = '7fa7f56194f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if table exists and drop if it does, to handle partially failed previous attempts
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'character_level' in inspector.get_table_names():
        op.drop_table('character_level')

    op.create_table('character_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('xp_at_level_up', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('hit_dice_rolled', sa.String(length=255), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('proficiencies', sa.Text(), nullable=True),
    sa.Column('features_gained', sa.Text(), nullable=True),
    sa.Column('spells_known_ids', sa.Text(), nullable=True),
    sa.Column('spells_prepared_ids', sa.Text(), nullable=True),
    sa.Column('spell_slots_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Data migration logic starts here
    bind = op.get_bind()
    
    # Define table structures for query and insert using a single MetaData object
    meta = sa.MetaData()
    character_table_old = sa.Table('character', meta,
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('level', sa.Integer),
        sa.Column('xp', sa.Integer),
        sa.Column('strength', sa.Integer),
        sa.Column('dexterity', sa.Integer),
        sa.Column('constitution', sa.Integer),
        sa.Column('intelligence', sa.Integer),
        sa.Column('wisdom', sa.Integer),
        sa.Column('charisma', sa.Integer),
        sa.Column('hp', sa.Integer),
        sa.Column('max_hp', sa.Integer),
        sa.Column('armor_class', sa.Integer),
        sa.Column('current_proficiencies', sa.Text)
    )

    character_level_table_new = sa.Table('character_level', meta,
        # Columns defined as in op.create_table, but for ORM-less operations
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True), # Ensure autoincrement for bulk_insert
        sa.Column('character_id', sa.Integer),
        sa.Column('level_number', sa.Integer),
        sa.Column('xp_at_level_up', sa.Integer),
        sa.Column('strength', sa.Integer),
        sa.Column('dexterity', sa.Integer),
        sa.Column('constitution', sa.Integer),
        sa.Column('intelligence', sa.Integer),
        sa.Column('wisdom', sa.Integer),
        sa.Column('charisma', sa.Integer),
        sa.Column('hp', sa.Integer),
        sa.Column('max_hp', sa.Integer),
        sa.Column('hit_dice_rolled', sa.String(255)),
        sa.Column('armor_class', sa.Integer),
        sa.Column('proficiencies', sa.Text),
        sa.Column('features_gained', sa.Text),
        sa.Column('spells_known_ids', sa.Text),
        sa.Column('spells_prepared_ids', sa.Text),
        sa.Column('spell_slots_snapshot', sa.Text),
        sa.Column('created_at', sa.DateTime)
    )

    # When in online mode, bind is already a connection.
    connection = bind 
    characters_result = connection.execute(sa.select(character_table_old)).mappings().all()

    character_level_inserts = []
    if characters_result: # Only proceed if there are characters
        for char_data in characters_result:
            character_level_inserts.append({
                'character_id': char_data['id'],
                'level_number': char_data['level'] if char_data['level'] is not None else 1,
                'xp_at_level_up': char_data['xp'] if char_data['xp'] is not None else 0,
                'strength': char_data['strength'] if char_data['strength'] is not None else 10,
                'dexterity': char_data['dexterity'] if char_data['dexterity'] is not None else 10,
                'constitution': char_data['constitution'] if char_data['constitution'] is not None else 10,
                'intelligence': char_data['intelligence'] if char_data['intelligence'] is not None else 10,
                'wisdom': char_data['wisdom'] if char_data['wisdom'] is not None else 10,
                'charisma': char_data['charisma'] if char_data['charisma'] is not None else 10,
                'hp': char_data['hp'] if char_data['hp'] is not None else 0,
                'max_hp': char_data['max_hp'] if char_data['max_hp'] is not None else 0,
                'hit_dice_rolled': None,
                'armor_class': char_data['armor_class'], 
                'proficiencies': char_data['current_proficiencies'] if char_data['current_proficiencies'] is not None else '{}',
                'features_gained': None,
                'spells_known_ids': "[]",
                'spells_prepared_ids': "[]",
                'spell_slots_snapshot': "{}",
                'created_at': datetime.datetime.utcnow()
            })

            # Update character's new fields directly using op.execute
            op.execute(
                character_table_old.update().
                where(character_table_old.c.id == char_data['id']).
                values(
                    dm_allowed_level=char_data['level'] if char_data['level'] is not None else 1,
                    current_xp=char_data['xp'] if char_data['xp'] is not None else 0
                )
            )

        if character_level_inserts:
            op.bulk_insert(character_level_table_new, character_level_inserts)

    # No connection.close() needed as bind is managed by Alembic's context.
    # Data migration logic ends here

    op.drop_table('character_prepared_spells')
    op.drop_table('character_known_spells')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dm_allowed_level', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('current_xp', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_column('strength')
        batch_op.drop_column('dexterity')
        batch_op.drop_column('current_proficiencies')
        batch_op.drop_column('wisdom')
        batch_op.drop_column('charisma')
        batch_op.drop_column('constitution')
        batch_op.drop_column('hp')
        batch_op.drop_column('max_hp')
        batch_op.drop_column('intelligence')
        batch_op.drop_column('level')
        batch_op.drop_column('xp')
        batch_op.drop_column('armor_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Data migration for downgrade is not explicitly defined here.
    # Downgrading would involve trying to reconstruct old fields from CharacterLevel,
    # which could be complex and lossy. Typically, only the most recent CharacterLevel
    # for each character would be used. For this exercise, we focus on the upgrade.

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('armor_class', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('xp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('intelligence', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('max_hp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('constitution', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('charisma', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wisdom', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('current_proficiencies', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('dexterity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('strength', sa.INTEGER(), nullable=True))
        batch_op.drop_column('current_xp')
        batch_op.drop_column('dm_allowed_level')

    op.create_table('character_known_spells',
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('spell_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'spell_id')
    )
    op.create_table('character_prepared_spells',
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('spell_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'spell_id')
    )
    op.drop_table('character_level')
    # ### end Alembic commands ###
