"""Add xp to Character

Revision ID: 437c1d331287
Revises: 
Create Date: 2025-05-27 16:32:41.855225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437c1d331287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hit_die', sa.String(length=10), nullable=True),
    sa.Column('proficiencies_armor', sa.Text(), nullable=True),
    sa.Column('proficiencies_weapons', sa.Text(), nullable=True),
    sa.Column('proficiencies_tools', sa.Text(), nullable=True),
    sa.Column('proficiency_saving_throws', sa.Text(), nullable=False),
    sa.Column('skill_proficiencies_option_count', sa.Integer(), nullable=False),
    sa.Column('skill_proficiencies_options', sa.Text(), nullable=False),
    sa.Column('starting_equipment', sa.Text(), nullable=False),
    sa.Column('spellcasting_ability', sa.String(length=20), nullable=True),
    sa.Column('spell_slots_by_level', sa.Text(), nullable=True),
    sa.Column('cantrips_known_by_level', sa.Text(), nullable=True),
    sa.Column('spells_known_by_level', sa.Text(), nullable=True),
    sa.Column('can_prepare_spells', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('ability_score_increases', sa.Text(), nullable=False),
    sa.Column('age_description', sa.Text(), nullable=True),
    sa.Column('alignment_description', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('size_description', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=False),
    sa.Column('traits', sa.Text(), nullable=True),
    sa.Column('skill_proficiencies', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('higher_level', sa.Text(), nullable=True),
    sa.Column('range', sa.String(length=100), nullable=True),
    sa.Column('components', sa.String(length=50), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('ritual', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('concentration', sa.Boolean(), nullable=True),
    sa.Column('casting_time', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('damage_type', sa.String(length=50), nullable=True),
    sa.Column('damage_at_slot_level', sa.Text(), nullable=True),
    sa.Column('school', sa.String(length=50), nullable=False),
    sa.Column('classes_that_can_use', sa.Text(), nullable=False),
    sa.Column('subclasses_that_can_use', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('current_proficiencies', sa.Text(), nullable=True),
    sa.Column('current_equipment', sa.Text(), nullable=True),
    sa.Column('alignment', sa.String(length=100), nullable=True),
    sa.Column('background_name', sa.String(length=100), nullable=True),
    sa.Column('background_proficiencies', sa.Text(), nullable=True),
    sa.Column('background_equipment', sa.Text(), nullable=True),
    sa.Column('adventure_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_known_spells',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'spell_id')
    )
    op.create_table('character_prepared_spells',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'spell_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_prepared_spells')
    op.drop_table('character_known_spells')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('spell')
    op.drop_table('setting')
    op.drop_table('race')
    op.drop_table('class')
    # ### end Alembic commands ###
