"""Remove Race, Class, and Spell tables and associated columns

Revision ID: 516caf886ac7
Revises: d6bb44b858aa
Create Date: 2025-06-01 10:55:45.743728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import NoSuchTableError, OperationalError


# revision identifiers, used by Alembic.
revision = '516caf886ac7'
down_revision = 'd6bb44b858aa'
branch_labels = None
depends_on = None


def upgrade():
    # Manual upgrade for SQLite to handle FKs and column drops from 'character'

    # 0. Drop character_temp if it exists from a previous failed run
    op.execute('DROP TABLE IF EXISTS character_temp')

    # 1. Create a new character table without the old FKs and columns
    op.create_table('character_temp',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('speed', sa.Integer(), nullable=False, server_default=sa.text("'30'")),
        sa.Column('alignment', sa.String(length=100), nullable=True),
        sa.Column('dm_allowed_level', sa.Integer(), nullable=False, server_default=sa.text("'1'")),
        sa.Column('current_xp', sa.Integer(), nullable=False, server_default=sa.text("'0'")),
        sa.Column('background_name', sa.String(length=100), nullable=True),
        sa.Column('background_proficiencies', sa.Text(), nullable=True), # JSON
        sa.Column('adventure_log', sa.Text(), nullable=True), # JSON
        sa.Column('current_hit_dice', sa.Integer(), nullable=False, server_default=sa.text("'1'")),
        sa.Column('player_notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. Copy data from old character table to new_character table
    cols_to_copy = "id, name, description, user_id, speed, alignment, dm_allowed_level, current_xp, background_name, background_proficiencies, adventure_log, current_hit_dice, player_notes"
    op.execute(f'INSERT INTO character_temp ({cols_to_copy}) SELECT {cols_to_copy} FROM character')

    # 3. Drop old character table
    op.drop_table('character')

    # 4. Rename new_character table to character
    op.rename_table('character_temp', 'character')

    # 5. Now drop the other tables, ignoring errors if they don't exist
    try:
        op.drop_table('class')
        print("Info: Table 'class' dropped or did not exist.")
    except Exception as e:
        print(f"Info: Could not drop table 'class' (it may have already been dropped): {e}")
        pass

    try:
        op.drop_table('spell')
        print("Info: Table 'spell' dropped or did not exist.")
    except Exception as e:
        print(f"Info: Could not drop table 'spell' (it may have already been dropped): {e}")
        pass

    try:
        op.drop_table('race')
        print("Info: Table 'race' dropped or did not exist.")
    except Exception as e:
        print(f"Info: Could not drop table 'race' (it may have already been dropped): {e}")
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-create tables first
    op.create_table('race',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('speed', sa.INTEGER(), nullable=False),
    sa.Column('ability_score_increases', sa.TEXT(), nullable=False),
    sa.Column('age_description', sa.TEXT(), nullable=True),
    sa.Column('alignment_description', sa.TEXT(), nullable=True),
    sa.Column('size', sa.VARCHAR(length=20), nullable=True),
    sa.Column('size_description', sa.TEXT(), nullable=True),
    sa.Column('languages', sa.TEXT(), nullable=False),
    sa.Column('traits', sa.TEXT(), nullable=True),
    sa.Column('skill_proficiencies', sa.TEXT(), nullable=True),
    sa.Column('parent_slug', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spell',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('index', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('higher_level', sa.TEXT(), nullable=True),
    sa.Column('range', sa.VARCHAR(length=100), nullable=True),
    sa.Column('components', sa.VARCHAR(length=50), nullable=True),
    sa.Column('material', sa.TEXT(), nullable=True),
    sa.Column('ritual', sa.BOOLEAN(), nullable=True),
    sa.Column('duration', sa.VARCHAR(length=100), nullable=True),
    sa.Column('concentration', sa.BOOLEAN(), nullable=True),
    sa.Column('casting_time', sa.VARCHAR(length=100), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('attack_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('damage_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('damage_at_slot_level', sa.TEXT(), nullable=True),
    sa.Column('school', sa.VARCHAR(length=50), nullable=False),
    sa.Column('classes_that_can_use', sa.TEXT(), nullable=False),
    sa.Column('subclasses_that_can_use', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('class',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hit_die', sa.VARCHAR(length=10), nullable=True),
    sa.Column('proficiencies_armor', sa.TEXT(), nullable=True),
    sa.Column('proficiencies_weapons', sa.TEXT(), nullable=True),
    sa.Column('proficiencies_tools', sa.TEXT(), nullable=True),
    sa.Column('proficiency_saving_throws', sa.TEXT(), nullable=False),
    sa.Column('skill_proficiencies_option_count', sa.INTEGER(), nullable=False),
    sa.Column('skill_proficiencies_options', sa.TEXT(), nullable=False),
    sa.Column('starting_equipment', sa.TEXT(), nullable=False),
    sa.Column('spellcasting_ability', sa.VARCHAR(length=20), nullable=True),
    sa.Column('spell_slots_by_level', sa.TEXT(), nullable=True),
    sa.Column('cantrips_known_by_level', sa.TEXT(), nullable=True),
    sa.Column('spells_known_by_level', sa.TEXT(), nullable=True),
    sa.Column('can_prepare_spells', sa.BOOLEAN(), nullable=True),
    sa.Column('level_specific_data', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('race_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_character_race_id_race', 'race', ['race_id'], ['id'])
        batch_op.create_foreign_key('fk_character_class_id_class', 'class', ['class_id'], ['id'])

    # Clean up character_temp if downgrade is interrupted then upgrade is tried again
    op.execute('DROP TABLE IF EXISTS character_temp')
    # ### end Alembic commands ###
