"""Refactor CharacterWeapon relationship to use Association Object

Revision ID: 5e2eebe23b68
Revises: 230199b4558a
Create Date: 2025-05-30 20:25:23.484303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2eebe23b68'
down_revision = '230199b4558a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old table if it exists (Alembic might not always detect this change correctly from Table to Model)
    op.drop_table('character_weapon_association')

    # Create the new table based on the CharacterWeaponAssociation model
    op.create_table('character_weapon_association',
        sa.Column('character_id', sa.Integer(), sa.ForeignKey('character.id'), primary_key=True, nullable=False),
        sa.Column('weapon_id', sa.Integer(), sa.ForeignKey('weapon.id'), primary_key=True, nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False, default=1),
        sa.Column('is_equipped_main_hand', sa.Boolean(), nullable=False, default=False),
        sa.Column('is_equipped_off_hand', sa.Boolean(), nullable=False, default=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new table
    op.drop_table('character_weapon_association')

    # Recreate the old table structure (as it was before this refactor)
    op.create_table('character_weapon_association',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('character_id', sa.Integer(), sa.ForeignKey('character.id'), nullable=False),
        sa.Column('weapon_id', sa.Integer(), sa.ForeignKey('weapon.id'), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=True, default=1), # Was nullable in original simple table
        sa.Column('is_equipped_main_hand', sa.Boolean(), nullable=True, default=False), # Was nullable
        sa.Column('is_equipped_off_hand', sa.Boolean(), nullable=True, default=False), # Was nullable
        sa.UniqueConstraint('character_id', 'weapon_id', name='uq_character_weapon')
    )
    # ### end Alembic commands ###
