"""add_missing_character_columns

Revision ID: 796273332cbd
Revises: e00b940bd17f
Create Date: 2025-05-24 18:44:40.904332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796273332cbd'
down_revision = 'e00b940bd17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temporary_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hit_dice_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hit_dice_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hit_dice_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prof_athletics', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_acrobatics', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_sleight_of_hand', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_stealth', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_arcana', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_history', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_investigation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_nature', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_religion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_animal_handling', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_insight', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_medicine', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_perception', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_survival', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_deception', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_intimidation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_performance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_persuasion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_strength_save', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_dexterity_save', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_constitution_save', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_intelligence_save', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_wisdom_save', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prof_charisma_save', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('death_saves_successes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('death_saves_failures', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proficiencies_armor_weapons_tools', sa.Text(), nullable=True))
        batch_op.drop_column('hp')
        batch_op.drop_column('proficiency_bonus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency_bonus', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hp', sa.INTEGER(), nullable=True))
        batch_op.drop_column('proficiencies_armor_weapons_tools')
        batch_op.drop_column('death_saves_failures')
        batch_op.drop_column('death_saves_successes')
        batch_op.drop_column('prof_charisma_save')
        batch_op.drop_column('prof_wisdom_save')
        batch_op.drop_column('prof_intelligence_save')
        batch_op.drop_column('prof_constitution_save')
        batch_op.drop_column('prof_dexterity_save')
        batch_op.drop_column('prof_strength_save')
        batch_op.drop_column('prof_persuasion')
        batch_op.drop_column('prof_performance')
        batch_op.drop_column('prof_intimidation')
        batch_op.drop_column('prof_deception')
        batch_op.drop_column('prof_survival')
        batch_op.drop_column('prof_perception')
        batch_op.drop_column('prof_medicine')
        batch_op.drop_column('prof_insight')
        batch_op.drop_column('prof_animal_handling')
        batch_op.drop_column('prof_religion')
        batch_op.drop_column('prof_nature')
        batch_op.drop_column('prof_investigation')
        batch_op.drop_column('prof_history')
        batch_op.drop_column('prof_arcana')
        batch_op.drop_column('prof_stealth')
        batch_op.drop_column('prof_sleight_of_hand')
        batch_op.drop_column('prof_acrobatics')
        batch_op.drop_column('prof_athletics')
        batch_op.drop_column('hit_dice_max')
        batch_op.drop_column('hit_dice_current')
        batch_op.drop_column('hit_dice_type')
        batch_op.drop_column('speed')
        batch_op.drop_column('temporary_hp')
        batch_op.drop_column('current_hp')

    # ### end Alembic commands ###
