"""Add parent_slug to Race model

Revision ID: d6bb44b858aa
Revises: a1afaee6caee
Create Date: 2025-06-01 10:18:42.890685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bb44b858aa'
down_revision = 'a1afaee6caee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_slug', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_column('parent_slug')

    # ### end Alembic commands ###
