"""Add AdventureLogEntry model

Revision ID: e00b940bd17f
Revises: 6934342e98a1
Create Date: 2025-05-23 14:56:02.782387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00b940bd17f'
down_revision = '6934342e98a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventure_log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('roll_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adventure_log_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adventure_log_entry_character_id'), ['character_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_log_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adventure_log_entry_character_id'))

    op.drop_table('adventure_log_entry')
    # ### end Alembic commands ###
