"""Add speed to CharacterLevel and consolidate API data handling

Revision ID: e5a2c32df34b
Revises: a1afaee6caee
Create Date: 2025-05-31 07:52:23.352158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a2c32df34b'
down_revision = 'a1afaee6caee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_level', schema=None) as batch_op:
        batch_op.drop_column('speed')

    # ### end Alembic commands ###
